'<div class="expand-lg collapse" id="categoriesMenu" role="menu">'
    '<h5 class="sidebar-heading d-none d-lg-block">Category </h5>'
    '<div class="sidebar-icon-menu mt-4 mt-lg-0">'
        '<div class="sidebar-icon-menu-item active" data-bs-toggle="collapse"'
           'data-bs-target="#subcategories_0" aria-expanded aria-controls="subcategories_0" role="menuitem">'
            '<div class="d-flex align-items-center">'
            '<svg class="svg-icon sidebar-icon">'
                '<use xlink:href="#trousers-1"></use>'
                '</svg>'
            '<a class="sidebar-icon-menu-link fw-bold me-2" href="#">Trousers</a>'
            '<span class="sidebar-icon-menu-count"> 120</span>'
            '</div>'
        '<div class="collapse show" id="subcategories_0">'
            '<ul class="sidebar-icon-menu sidebar-icon-submenu">'
                '<li class="sidebar-icon-submenu-item">'
                    '<a class="sidebar-icon-submenu-link link-animated link-animated-light"'
                    'href="#">'
                    'Lorem ipsum'
                    '</a>'
                    '</li>'
                '</ul>'
            ' </div>'
        '</div>'
    '</div>'
'</div>'
