
SET
FOREIGN_KEY_CHECKS=0;
SET
SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET
time_zone = "+00:00";
CREATE TABLE company
(
    COMP_ID                 INT AUTO_INCREMENT PRIMARY KEY,
    COMP_NOMBRE             VARCHAR(255) NOT NULL,
    COMP_RNC                VARCHAR(20)  NOT NULL UNIQUE,
    COMP_ANO                INT,
    COMP_PERIODO            INT,
    COMP_CIERRE_FISCAL      INT,
    COMP_CALLE              VARCHAR(255),
    COMP_SECTOR             VARCHAR(255),
    COMP_CORREO             VARCHAR(100),
    COMP_TELEFONO1          VARCHAR(20),
    COMP_TELEFONO2          VARCHAR(20),
    COMP_FAX1               VARCHAR(20),
    COMP_FAX2               VARCHAR(20),
    COMP_IMPRESIONLOGO      INT,
    COMP_CUENTA_CIERRE      VARCHAR(50),
    COMP_CUENTA_DIFERENCIAS VARCHAR(50),
    COMP_WEBSITE            VARCHAR(100),
    COMP_NPA                VARCHAR(50),
    NAC_ID                  INT,
    MONE_ID                 INT,
    PAIS_ID                 INT,
    CIUD_ID                 INT
);
CREATE TABLE product_codebar
(
    ID             INT AUTO_INCREMENT PRIMARY KEY,
    PRBA_CODIGO    VARCHAR(20)    NOT NULL,
    PROD_ID        INT            NOT NULL,
    PROD_NOMBRE    VARCHAR(255)   NOT NULL,
    PROD_PRECIO    DECIMAL(10, 2) NOT NULL,
    COMP_RNC       VARCHAR(20)    NOT NULL,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (COMP_RNC) REFERENCES company (COMP_RNC)
);

ALTER TABLE product_codebar
    ADD COLUMN UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
SET
FOREIGN_KEY_CHECKS=1;
COMMIT;

